import '@/styles/globals.css';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import Provider from '@/components/Provider';
import Narbar from '@/components/Narbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'similarity.io',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn('bg-white text-slate-900 antialiased', inter.className)}
    >
      <body className="min-h-screen bg-slate-50 dark:bg-slate-900 antialiased">
        <Provider>
          {/* @ts-expect-error Server Component */}
          <Narbar />
          {children}
        </Provider>
        {/* Allow for more height ob mobile devices */}
        <div className="h-40 md:hidden" />
      </body>
    </html>
  );
}
